steps:
  - name: 'gcr.io/qwiklabs-resources/packer'
    args:
    - build
    - -var
    - image_name=theia-java-dataflow-v$_TIMESTAMP
    - -force
    - packer.json
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - compute
    - images
    - add-iam-policy-binding
    - theia-java-dataflow-v$_TIMESTAMP
    - --member=allAuthenticatedUsers
    - --role=roles/compute.imageUser